### ISSUE TITLE
can u make aimbot arduino for valorant ?

### ISSUE THREAD

**Issue by NexMou** [thayes46/aimi#27]
i find in internet and no one get source code arduino for valorant.

**Comment by thayes46** [comment]
This project does not interact with the source code of the game, as that would explicitly break terms of service and is illegal.

**Comment by gaetgu** [comment]
I think he was trying to say that there should be a physical aimbot based off an arduino, kinda like the cronus.

**Comment by thayes46** [comment]
We actually hadn't heard of the cronus until you mentioned it, this is moreso intended to completely mimic human interaction, down to using a physical robot arm to be able to move a mouse. Moreso an educational exploration without any commercial motivation
